# Generated by Django 5.2.5 on 2025-08-28 06:50

import Authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[Authentication.models.validate_zafiri_email])),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('department', models.CharField(choices=[('planning', 'Planning and Administration'), ('laboratory', 'Laboratory'), ('research', 'Department of Research'), ('directorate', 'Directorate General')], default='planning', max_length=30)),
                ('position', models.CharField(choices=[('planning_officer', 'Planning Officer'), ('statistic_officer', 'Statistic Officer'), ('head_division_planning', 'Head of Division (Planning)'), ('head_division_administration', 'Head of Division (Administration)'), ('head_department_planning', 'Head of Department (Planning & Admin)'), ('register', 'Register'), ('laboratory_technician', 'Laboratory Technician'), ('head_division_laboratory', 'Head of Division (Laboratory)'), ('head_department_laboratory', 'Head of Department (Laboratory)'), ('researcher', 'Researcher'), ('assistant_researcher', 'Assistant Researcher'), ('head_division_research', 'Head of Division (Research)'), ('head_department_research', 'Head of Department (Research)'), ('director_general', 'Director General')], default='planning_officer', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
