# Generated by Django 5.2.5 on 2025-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='phone_number',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
    ]
