# Generated by Django 5.2.5 on 2025-09-29 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_authenticateduser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authenticateduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='authenticateduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authenticateduser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
